# Generated by Django 2.1.2 on 2018-12-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chahana', '0002_remove_profile_register_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
