# Generated by Django 2.1.2 on 2018-12-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chahana', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
