# Generated by Django 2.1.2 on 2018-12-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chahana', '0005_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
