# Generated by Django 2.1.2 on 2019-01-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chahana', '0008_auto_20181231_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_list',
            name='user_id',
        ),
    ]
