# Generated by Django 2.1.2 on 2019-01-01 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chahana', '0009_remove_wish_list_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_list',
            name='user_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
