# Generated by Django 2.1.2 on 2019-01-01 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chahana', '0010_wish_list_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
